version: '3'

services:
  upload:
    container_name: upload-service
    ports:
      - 80:3000
    build:
      context: .
    environment:
      AWS_S3_BUCKET_NAME: insta-dev
      AWS_S3_REGION: ap-southeast-1
      AWS_S3_SECRET_ACCESS_KEY: AXFEkYbmPoLGNoAh3PoF+x18TSagcsOEBH14P0Ez
      AWS_S3_ACCESS_KEY_ID: AKIAXYKJWYHSB4XJMBXE
      URL_PUBLIC: https://d2q1znnx4jye0q.cloudfront.net
